name: green_guard
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-42.2.beta <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.2
  file_picker: ^8.0.0+1
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  google_generative_ai: ^0.2.0
  http: ^1.0.0
  http_parser: ^4.0.0
  image_cropper: ^1.4.1
  image_picker: ^1.0.7
  translator: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons : ^0.9.2

flutter_icons:
  android : true
  ios: true
  image_path : "assets/logo1.png"
  adaptive_icon_background : "#ffffff"
  adaptive_icon_foreground : "assets/logo1.png"

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

